"""Core data objects shared by every stage of the pipeline.

The field names in `Finding` that come straight from CodeChecker
(`checker_name`, `severity`, `report_hash`, ...) intentionally mirror the
JSON keys produced by `CodeChecker parse --export json`, which is
generated by `Report.to_json()` in the CodeChecker source
(tools/report-converter/codechecker_report_converter/report/__init__.py).
Keeping the names aligned makes `scanner/codechecker.py` a near-literal
translation instead of an ad-hoc remapping, which matters if a future
CodeChecker version changes report internals but not this JSON contract.
"""

from __future__ import annotations

import enum
import hashlib
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path


class FindingStatus(str, enum.Enum):
    """Lifecycle of a single CodeChecker finding through the pipeline."""

    OPEN = "open"  # Scanned, not yet dispatched to a model.
    IN_PROGRESS = "in_progress"  # A model is currently attempting a fix.
    FIXED = "fixed"  # A patch passed build + tests + re-scan.
    FAILED = "failed"  # Ran out of attempts without a passing patch.
    REGRESSED = "regressed"  # A patch "fixed" the target but broke
    # something else (build/tests/new findings); kept distinct from FAILED
    # so the scorer can report regression rate separately from plain
    # failure-to-fix, since the former is the more serious trust signal.
    SKIPPED = "skipped"  # Excluded from this run (e.g. finding_limit).


class VerificationStage(str, enum.Enum):
    """Which gate a verification attempt got to / failed at.

    Ordered the same way the Verifier runs them, so `stage` also tells you
    how far a patch got even when it ultimately failed.
    """

    PATCH = "patch"  # The diff itself didn't apply cleanly.
    BUILD = "build"
    TEST = "test"
    RESCAN = "rescan"
    PASSED = "passed"  # All gates cleared.


@dataclass
class BugPathEvent:
    """One step of CodeChecker's source-to-sink bug path trace.

    Mirrors the `bug_path_events[]` entries in CodeChecker's JSON report
    (each has file/line/column/message) -- this is the "how the analyzer
    got here" trail that gives the LLM more than just the final line.
    """

    file_path: str
    line: int
    column: int
    message: str


@dataclass
class Finding:
    """One CodeChecker finding, normalized and (if applicable) tagged with
    the SEI CERT rule it corresponds to.

    `cert_rule_ids` is populated by `scanner.cert_mapping.CertRuleMapper`,
    not by CodeChecker's report JSON directly -- CodeChecker only tells you
    which *checker* fired; the checker-to-CERT-rule mapping lives in its
    checker label data and has to be joined in separately (see
    scanner/cert_mapping.py for exactly how).
    """

    # Stable identity CodeChecker computes from checker name + location +
    # surrounding code (see report_identification in CodeChecker docs).
    # Used as the primary key in FindingStore and to re-match a finding
    # across a before/after re-scan diff.
    report_hash: str

    file_path: str
    line: int
    column: int
    message: str
    checker_name: str
    analyzer_name: str
    severity: str

    # CERT rule id(s) this checker enforces, e.g. ["STR31-C"]. A checker
    # can map to more than one rule, and a rule can be enforced by more
    # than one checker, so this is a list, not a single value. Empty if the
    # checker isn't part of the configured CERT guidelines (such findings
    # are filtered out before dispatch -- see scanner.codechecker.Scanner).
    cert_rule_ids: list[str] = field(default_factory=list)
    cert_guideline: str = ""  # "sei-cert-c" or "sei-cert-cpp".

    bug_path_events: list[BugPathEvent] = field(default_factory=list)
    status: FindingStatus = FindingStatus.OPEN

    def primary_cert_rule(self) -> str:
        """First/most relevant CERT rule id, or "UNMAPPED" if none.

        Used anywhere a single grouping key is needed (e.g. the scorer's
        per-rule breakdown) since most findings map to exactly one rule.
        """
        return self.cert_rule_ids[0] if self.cert_rule_ids else "UNMAPPED"


@dataclass
class FixAttempt:
    """One LLM's attempt to patch a single Finding."""

    finding_hash: str  # Finding.report_hash this attempt targets.
    model_name: str  # ModelConfig.name (human label, not model_id).
    attempt_number: int  # 1-indexed; first attempt has no prior feedback.

    # Unified diff (preferred) or full replacement source the model
    # produced. Stored verbatim (not just applied-and-discarded) so a
    # human can audit exactly what a model proposed, even for attempts
    # that were rejected by the verifier.
    patch_text: str

    # Full text sent to the model for this attempt, including any
    # prior-failure feedback folded in on retries. Kept for reproducibility
    # and prompt debugging.
    prompt_text: str
    raw_model_response: str

    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


@dataclass
class VerificationResult:
    """Outcome of running the Verifier against one FixAttempt."""

    finding_hash: str
    model_name: str  # Disambiguates attempts when >1 model targets the
    # same finding_hash; (finding_hash, model_name, attempt_number) is the
    # natural key used by FindingStore.
    attempt_number: int
    stage_reached: VerificationStage
    passed: bool

    # Human-readable detail for the stage that failed (compiler error text,
    # failing test name/output, or a description of new findings). This is
    # exactly what gets fed back to the model on the next retry, so it
    # should be concise and actionable rather than a raw dump.
    detail: str

    # True only when the *original* finding no longer appears in the
    # re-scan. Distinct from `passed`, because a patch can make the
    # original finding disappear while still failing the build/tests, or
    # (more subtly) can pass build+tests while not actually touching the
    # flagged line -- `target_resolved=False` in that case flags a
    # no-op/irrelevant patch rather than crediting a false pass.
    target_resolved: bool = False

    # New findings CodeChecker reports after the patch that were not in
    # the pre-patch baseline scan. Any non-empty list here means the
    # attempt regressed the codebase even if target_resolved is True.
    new_findings: list[Finding] = field(default_factory=list)

    duration_seconds: float = 0.0
    patch_text: str = ""
    touched_files: list[str] = field(default_factory=list)
    artifact_path: str = ""
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )


def normalized_finding_identity(finding: Finding, project_root: Path) -> str:
    """Identity stable across disposable worktree prefixes and line shifts."""
    root = Path(project_root).resolve()
    path = Path(finding.file_path)
    if not path.is_absolute():
        relative = path
    else:
        try:
            relative = path.resolve().relative_to(root)
        except ValueError:
            # A rescan path may come from another checkout. Retain the longest
            # project-relative suffix by anchoring at a known source directory.
            parts = path.parts
            root_name = root.name
            relative = (
                Path(*parts[parts.index(root_name) + 1:])
                if root_name in parts
                else Path(path.name)
            )
    message = re.sub(r"\s+", " ", finding.message.strip().lower())
    material = f"{finding.checker_name}\0{relative.as_posix()}\0{message}"
    return hashlib.sha256(material.encode()).hexdigest()
